- name: variables
  hosts: web
  vars_file:
  - vars.yaml
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Hello, I have started the {{COURSE}}-Course, time period is:{{DURATION}}"