- name: datatypes
  hosts: web
  vars:
    course: "DevOps"
    duration: 120HRS
    topics:
    - linux
    - shell
    - ansible
    tools:
      ci: jenkins
      cm: ansible
    live: true
  tasks:
  - name: datatypes
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, topics are {{topics}}, tools are {{tools}}, durationis {{duration}} and live classes:{{live}}"
  