- name: Create ec2 instances for DoctorAppointment project
  hosts: local
  connection: local
  vars:
    instaces:
    - mysql
    - backend
    - frontend
    ami_id: "ami-0220d79f3f480ecf5"
    security_id: "sg-0143c6df8abb26414"
    vpc_subnet_id: "subnet-0ebfcdb20a210d658"
    instance_type: t3.small
    zone_id: "bavs.space"

  tasks:
  - name: install python dependencies
    ansible.builtin.pip:
      name: "{{item}}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: "{{instance_type}}"
      image_id: "{{ ami_id }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      security_group: "{{ security_id }}"
    loop: "{{ instaces }}"
    register: ec2_instances

  - name: print the instances
    ansible.builtin.debug:
      msg: "created instaces are {{ec2_instances}}"

  - name: create route53 records for internal
    amazon.aws.route53:
      state: present
      zone: "{{zone_id}}"
      record: "{{item.item}}.{{zone_id}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
  
  - name: create route53 record for end user
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instaces[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
    when: ec2_instances.results is frontend